- name: Add Rancher Helm repository
  command: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

- name: Create cattle-system namespace
  command: kubectl create namespace cattle-system

- name: Install cert-manager
  command: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.10.1/cert-manager.crds.yaml

- name: Add Helm repository
  command: helm repo add jetstack https://charts.jetstack.io

- name: Update Helm repositories
  command: helm repo update

- name: Add Helm repository
  command: helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.10.1

- name: kube permission
  command:  chmod 600 /root/.kube/config

- name: Wait for Rancher to be ready
  command: sleep 60 

- name: Install Rancher
  command: helm install rancher rancher-stable/rancher --version {{ rancher_version }} --namespace cattle-system --set hostname={{ rancher_domain }} --set ingress.tls.source=secret --set ingress.tls.secretName=tls-rancher-ingress

- name: Wait for Rancher to be ready
  command: kubectl -n cattle-system wait --for=condition=ready pod -l app=rancher --timeout=300s

